### ISSUE TITLE
Allyson Finck: IBM Takeaway

### ISSUE THREAD

**Issue by allysonfinck** [ga-students/wdiroutcomes#118]
By the end of our IBM Tour - what Ale said about creating our own projects on the side in addition to our GA projects really stuck out to me. Up until yesterday, I really thought we had so many things to show I never considered staking out on my own and doing a completely different project. This not only shows drive on my part to a future employer but I can also tackle whatever problem/solution I want and incorporate anything - so I can really take it as an opportunity to learn something new or continue perfecting something I enjoy doing. This changed my whole outlook on how I want to spend my time when I am not in class or working on a project or homework for GA.

**Comment by nicoleump** [comment]
Exactly! Class projects are one thing but having your own projects is also important! It shows creativity and passion!
