### ISSUE TITLE
Rachel Elam | IBM TAKEAWAY

### ISSUE THREAD

**Issue by relam24** [ga-students/wdiroutcomes#122]
After our outcomes class of the IBM Tour, I really took away that I think I want to get an internship before I get a full time job just for the summer. I want to really learn from other developers in a professional environment and I think getting an internship like IBM would be a great way to do that.

**Comment by nicoleump** [comment]
Internships are a great way to gain experience and basically get paid to train. Many folks choose to go this route post-course as a way to further build their skills and get their foot in the door with a company.
