### ISSUE TITLE
Shaun Savage - IBM Takeaway

### ISSUE THREAD

**Issue by swansavage** [ga-students/wdiroutcomes#124]
What a great info session from IBM! It was great to hear Ale's points about where she was before finding her internship at IBM and where she is now. My biggest takeaway from her is that companies (or at least IBM) are looking to invest in an employee and have an awesome support system for developing your skills further. A lot of what Taylor had to say really firmed this up for me too after hearing her explain the internships and hiring process from her point of view.

**Comment by nicoleump** [comment]
Yes, IBM has developed a great on-boarding and training program for new employees as well as their internship program. Glad you enjoyed the session.
