### ISSUE TITLE
Brian Murphy: IBM Takeaway

### ISSUE THREAD

**Issue by BrianMurphy89** [ga-students/wdiroutcomes#125]
I've been having some doubts about finishing the course and feeling prepared to be hired has a programmer. It was great to hear that IBM offers an internship program that is essentially another bootcamp that is paid! Really gave me something to think about in terms of what jobs to potentially look for after the course is completed.

**Comment by nicoleump** [comment]
Thanks for the honesty, Brian. I have worked with others who felt the same as you and an internship is a great way to get experience (basically getting paid to train). I'd encourage you to explore other companies who have internship programs.
