### ISSUE TITLE
Trenton Marks -- IBM Takeaway

### ISSUE THREAD

**Issue by TrentonMarks** [ga-students/wdiroutcomes#126]
I think it was awesome that you were able to set up such an in-depth and revealing interview from IBM.  It was really intriguing to me to experience a major software engineering company and the way that they manage their operations.  It was also pretty eye opening that they offer a 6-week paid training internship in Austin and then let you go back to where you came from.  Please message me and let me know if IBM's internship leads to a remote opportunity upon completion! Thank you!

**Comment by nicoleump** [comment]
As for the internship, typically if things go well, you either are brought on for the Austin office or you go back to where you came from and work in the office in your city. If there is not a IBM in your area, then you complete the internship and that's it. They used to allow for remote working but moved away from that as they really like having people collaborate in the office.
