### ISSUE TITLE
Victor Jaquez: Cover Letter

### ISSUE THREAD

**Issue by victorjaquez** [ga-students/wdiroutcomes#136]
https://docs.google.com/document/d/1bKzYo7OHqTYCKEsC2KZM-2tDrKtfyev2IJBweWQl4uY/edit?usp=sharing

**Comment by nicoleump** [comment]
Here's my feedback:
- No need to have the header with your name and contact info listed. No date either.
- Instead of "Dear Recruiter" how about "Dear Consensys Team"
- Break up your paragraphs a bit more by indenting them or adding a line space between each one.
