### ISSUE TITLE
Shaun Savage: Cover Letter

### ISSUE THREAD

**Issue by swansavage** [ga-students/wdiroutcomes#139]
cover letter:
https://docs.google.com/document/d/1ZKYd9ue2puPgA4PGl9jv0C5ZUexG0cmSc_4T0N58JaQ/edit?usp=sharing

link to job posting:
https://jobs.lever.co/myemma/7cc7ab12-4277-4941-b7b6-727a5c79886a

**Comment by nicoleump** [comment]
Overall great job! The first paragraph it a bit long. Perhaps break that up into two or remove some of the content.
