### ISSUE TITLE
Rachel Elam- Cover Letter 

### ISSUE THREAD

**Issue by relam24** [ga-students/wdiroutcomes#141]
[Cover Letter.pdf](https://github.com/ga-students/wdiroutcomes/files/1921275/Cover.Letter.pdf)

**Comment by nicoleump** [comment]
Here's my feedback:
- No sir/madam instead "Good Morning (company name) Team" 
- First sentence sounds robotic. Instead "I'm excited to express my interested in your current software development opening." Then you immediately go into talking about yourself. Instead add why you are interested in the role and show that you've done your research on the company. 
- Make sure paragraph two and three has content that relates directly to the job posting.
