### ISSUE TITLE
Teilachanell Angel||Homework

### ISSUE THREAD

**Issue by tnangel1984** [ga-students/wdiroutcomes#147]
Questions for Panelist:
Describe the culture of your companies
In what ways do your companies provide opportunities for employees to continue to learn and advance theirs skills? (i.e. internal/external training programs, mentor programs, tuition re-imbursement etc.)
What do you see as the biggest challenges facing incoming programmers in your companies?

Link to Blog Post:
https://medium.com/@tnangel1984123/how-to-travel-during-a-web-dev-bootcamp-and-why-its-a-bad-idea-713e4a3acbd1
(sorry not my best writing so it's very long)

**Comment by nicoleump** [comment]
Thanks for the great questions and the second blog post. I love the lessons learned!
