### ISSUE TITLE
Erin McMackin: Panel Questions

### ISSUE THREAD

**Issue by erinmcmackin** [ga-students/wdiroutcomes#149]
1. How do you determine who will be asked to interview and who will be cut based on their application?
2. What is the technical interview like? For example, do you give a code challenge with a day or two to complete or is it given and evaluated on the spot?
3. Tim, what has your experience been as an entrepreneur? Were you expecting to have such a large company when you started out?

**Comment by nicoleump** [comment]
Gret questions, Erin.
