### ISSUE TITLE
Samantha Whindleton: Panel Questions

### ISSUE THREAD

**Issue by samwhindleton** [ga-students/wdiroutcomes#150]
| Person/Company | Question |
| --- | --- |
| Tim Hamilton, CEO of Praxent | One of the many services that Paraxent provides is web app development. Does this provide your developers the opportunity to work with a variety of technologies? If so, what would you say the positives and negatives are about being able to work with so many different technologies? |
| Molly Hitchings, Recruiter with Mathys + Potestio | Other than the 6 reason Mathys+Potestio is different than other staffing agencies. What would you say makes Mathys+Potestio really shine compared to other staffing agencies. And what do you say is the most important thing(skill, experience, work style, availability for the position, attitude and professional approach, etc.) you look for in potential talent? |
| Katy Kendall, Recruiter with Under Armour |  Under Armors current global training campaign is a challenge to answer "How are you going to get here?" As a soon to be graduate of a full-time immersive web development course from General Assembly. How can we get there? (What does Under Armor look for when interviewing/hiring recent graduates?) |

**Comment by nicoleump** [comment]
Very well thought out questions, Sam. I can see you did your company research and really thought through things.
