### ISSUE TITLE
Allan Wolfe Cover Letter 

### ISSUE THREAD

**Issue by awolfe89** [ga-students/wdiroutcomes#155]
Thank you for taking the time to look at my resume, I am very excited to be applying. 

My name is Allan Wolfe and I’ve been a digital marketer for 6+ years and I've been in marketing as a Director for 3-4 years working alongside start-ups and multi-million dollar companies alike. In my free time I have also consulted and freelanced in marketing, PPC, web development and SEO 

I am constantly keeping up with the latest in marketing & SEO as well as building web apps with new languages and taking courses to extend my depth of understanding development. I recently also became a full stack web developer to push my skills further than most digital marketers I have seen.

I am currently the eCommerce/Marketing Manager for a large online- HVAC retailer in charge of data, marketing, SEO and product lines for around 11,000 products. I have worked with start ups, to 8-figure companies. 

Please feel free to browse my website I custom built to show my skills & interests further

www.getwolfe.com

Feel free to contact me at anytime.

-Allan Wolfe

**Comment by nicoleump** [comment]
In sentence one - you didn't even tell me what role you are applying for. From there, tell me why you are interested in the role and my company before immediately talking about yourself. 

You are focusing heavily on marketing and SEO, which is fine if that directly relates to the job posting. Just make sure to customize this content based on what the job ad says and what the company is looking for. 

You then tell me you are currently a marketing manager - then why are you applying to my job? Again, make sure to always bring it back to the employer and why you would be a fit. Tie your skills and experience back to the job ad. It's not all about you. 

Wrap things up in a professional way, with a sign off like Sincerely, Thanks, or Best.
