### ISSUE TITLE
Brian Murphy: Panel Questions

### ISSUE THREAD

**Issue by BrianMurphy89** [ga-students/wdiroutcomes#160]
1. When interviewing candidates, what qualities are you looking to flesh out that that would help you evaluate a candidate to be a good fit or not.

2. If a candidate does not do well in an interview but did follow up with anyone involved in the interviewing process and acknowledged that they could have done better. Does that factor into your decision about that candidate or is it all about first impressions?

3. If someone's technical skills are not exactly what you are looking for but they check off other attributes you are looking for, how willing / flexible are you with bringing that candidate along to refine those skills that are lacking?

**Comment by nicoleump** [comment]
Great, thanks.
