### ISSUE TITLE
Teilachanell|CoverLetter|

### ISSUE THREAD

**Issue by tnangel1984** [ga-students/wdiroutcomes#161]
Again not my best, and not100% on target, but I wanted to submit something for feedback rather than keep picking at it.

https://drive.google.com/open?id=1GetfjC93wppeAAXK-aU8hars6zpzZEWx

**Comment by nicoleump** [comment]
Here's my feedback starting at the top:
-No need for your address. Name, email, and phone is fine. Or you could remove the header altogether.
-In paragraph one, you immediately jump in talking about you. In this paragraph you need to show your excitement for the role and company. Show you've done your research here.
-With the remaining 1-2 paragraphs, tie in your skills and experience to the job ad. Mention things that are outside of your resume and that directly relate to the job ad. 
-I like the way you wrapped things up.
