### ISSUE TITLE
Rachel Elam- FINAL LinkedIn

### ISSUE THREAD

**Issue by relam24** [ga-students/wdiroutcomes#38]
https://www.linkedin.com/in/rachelselam/

**Comment by nicoleump** [comment]
Great job, Rachel. A few future things to remember:
-add your brand statement to your summary section one that's ready. 
-add links to your projects in the GA section in Experience
-turn off endorsements in the skills section so you have a nice clean list of skills
-get recommendations from classmates/instructors
