### ISSUE TITLE
Benjamin Peters Brand Statement Draft

### ISSUE THREAD

**Issue by benpeterswake** [ga-students/wdiroutcomes#41]
top 5:
information Systems,
amazon web services,
web dev internship,
creative,
innovative

I enjoy learning and working with new technologies, which is why I decided to peruse a degree in information systems and attend the general assembly web development immersive. My appetite for innovation lead me to obtain my Amazon Web Services developer certification, which I hope to use to continue my momentum and become known as a reliable and respectable full stack web developer.

**Comment by nicoleump** [comment]
Example: As a web and AWS-certified developer, I enjoy learning and working with new technologies that allow me to innovate and create. 

Remember to answer these questions: 
What do you do? What problem do you solve? How are you different? Why should an employer care?
