### ISSUE TITLE
Samantha Whindleton | Week 3 Homework | Final Brand Statement

### ISSUE THREAD

**Issue by samwhindleton** [ga-students/wdiroutcomes#42]
| Outcomes Homework | Answers |
| --- | --- | 
| DRAFT Brand Statement | Hi there! I’m Sam, a hard-working, tech-savvy full stack web developer. Graduate of a full-time, thirteen-week immersive Full Stack Web Development course at General Assembly. Constantly looking for better ways to solve problems, and opportunities to learn and grow. Let's ./start.sh something new." |
| FINAL LinkedIn Profile, send Nicole an invite to connect, and submit customized url | [Final Linkedin Link](https://www.linkedin.com/in/samwhindleton/) |

**Comment by nicoleump** [comment]
Amazing job on your LinkedIn Profile, Sam! Love it! The only note is to remember to get recommendations from classmates and instructors as well as former colleagues/managers (if possible) as a way to build a more credible profile.

**Comment by victorjaquez** [comment]
Almost perfect brand statement, maybe change websites to web applications, or something more broad.. besides that love it!
