### ISSUE TITLE
Erin McMackin - Draft Brand Statement

### ISSUE THREAD

**Issue by erinmcmackin** [ga-students/wdiroutcomes#43]
Strong-willed and optimistic, nothing can stop my drive to continually improve myself and my surroundings. I'm a voracious learner and I use my curiosity to form inventive solutions to problems new and old. Web development is the playground where I exercise these traits in a productive environment.

**Comment by relam24** [comment]
Really good use of language. I also like that you put 'web development is the playground where I exercise these traits"

**Comment by tnangel1984** [comment]
Hey! Looks like we have something in common. This is good work I love the energy in it very powerful. My only reccos would be to try out different synonyms for strong-willed and see if they work (as it can have multiple connotations). Maybe determined, or persevering, to tenacious?  Also incorporate some of the statements from your linkedIn summary  particularly: foresight and from multiple perspectives. and unmovable core belief in improving the world around me. I really liked those. :)

**Comment by nataliewolff20** [comment]
This is really concise but also shows your passion and desire to be amazing at whatever it is you are about to do! Well done :)
