### ISSUE TITLE
Natalie Wolff - Brand Statement Draft

### ISSUE THREAD

**Issue by nataliewolff20** [ga-students/wdiroutcomes#45]
I utilize a team-mindset in my professional roles drawing upon my coaching skills and leading by example. I am also optimistic in all areas, highly adaptable and bring a joyful sense of humor to the table which allows me to be a key member of any team.

**Comment by relam24** [comment]
I like that you are putting light to your coaching skills and where you've been successful in the past.

**Comment by nataliewolff20** [comment]
*I am a web developer
