### ISSUE TITLE
Tate Wilson - Final LinkedIn

### ISSUE THREAD

**Issue by tatewilson4** [ga-students/wdiroutcomes#48]
www.linkedin.com/in/wilsontate

**Comment by nicoleump** [comment]
Thanks Tate. A few items to fix up:
-Your headline shouldn't be title at company. Something like "Web Developer" or "Front-End Developer \ JavaScript Lover" is what we're shooting for here.
-Add your brand statement to your summary section one that's ready. 
-For GA in Experience, the logo isn't showing correctly so try removing and re-adding it. Also, add a description about the program.
-Add descriptions for your past roles (focusing on evidence of impact). 
-Don't forget recommendations from classmates/instructors as well.

**Comment by tatewilson4** [comment]
Awesome, thank you for the feedback. I will get all of those done as soon
as possible!
