### ISSUE TITLE
Tate Wilson - Draft Brand Statement

### ISSUE THREAD

**Issue by tatewilson4** [ga-students/wdiroutcomes#49]
I am a hard-working individual who exceeds in problem solving situations. When it comes to work-related values, I often find myself trustworthy, patient and mindful to others. My mindset is typically creative with a focus of entrepreneurship.

**Comment by erinmcmackin** [comment]
Sweet and to the point! You could make it a little stronger by removing things like "find myself" and "typically." Seems really genuine!
