### ISSUE TITLE
Olena Penn | Draft Brand Statement

### ISSUE THREAD

**Issue by op9674a** [ga-students/wdiroutcomes#50]
I am a web developer who strives for thoughtful, simple design  for products that foster positive social impact. I enjoy facilitating conversation between different groups to connect and find common ground to solve mutual issues or just for the sake of connecting!  When myself or others are faced with challenges, I am willing to help in any capacity while maintaining a sense of humor.

**Comment by allysonfinck** [comment]
I like how you found an original way to highlight collaboration as a skill and connect it to the web development world!

**Comment by swansavage** [comment]
Great job, it really highlights that you're a team player and work well with others! I feel like you've given a great idea of who you are (in my experience working with you in class) and can 100% speak to this statement.
