### ISSUE TITLE
Allan Wolfe LinkedIn Profile 

### ISSUE THREAD

**Issue by awolfe89** [ga-students/wdiroutcomes#52]
https://www.linkedin.com/in/allan-web-dev/

Draft Statement

"eCommerce Dev | Good with marketing/start-ups / & wide array of unique experiences . Self starter and a tireless work-ethic "

**Comment by nicoleump** [comment]
Feedback on your LinkedIn Profile:
-Overall great job!
-For the role with HVACnet, there's no dates or description so I recommend you add both or remove the role. GA should be the first role currently listed. 
-Add links to your projects in the GA section in Experience
-Get recommendations from classmates/instructors

**Comment by samwhindleton** [comment]
Feedback for brand statement.
Brand statement is short and to the point. Expanding on "wide array of unique experiences" would be fantastic! Overall great brand statement, shows you are ready to get to work!

**Comment by victorjaquez** [comment]
Feedback on statement. 
Should add new technologies you now learned and will know by the time course is over, its great you know Magento but we've learned and will learn more cool stuff you can add. Love the touch of family in it as well, makes it very wholesome and genuine.
