### ISSUE TITLE
Allyson Finck Week 3 Homework

### ISSUE THREAD

**Issue by allysonfinck** [ga-students/wdiroutcomes#53]
Brand Statement:
I’m a web developer passionate about innovation. I seek new and more difficult challenges to grow as a person and a problem solver. My goal in life is to always be learning - from new technology, people and ideas. As a leader I drive to inspire myself and others to forge creative and innovative paths to grow as developers.

Linkedin Profile:
https://www.linkedin.com/in/allyson-finck/

**Comment by op9674a** [comment]
Love that you mention that you are a problem solver because it is definitely true (re: Space Battle)! I think it's good as is but if you wanted to add anything, something about your management experience and people skills required for that would fit in nicely.

**Comment by nicoleump** [comment]
Feedback on your LinkedIn Profile:
-overall, great job!
-add links to your projects in the GA section in Experience
-get recommendations from classmates/instructors
