### ISSUE TITLE
Trenton Marks -- Final LinkedIn

### ISSUE THREAD

**Issue by TrentonMarks** [ga-students/wdiroutcomes#56]
https://www.linkedin.com/in/trentonmarks/

Have not added photos! I need to take some professional pictures and then I will have them up.

**Comment by nicoleump** [comment]
Thanks for the note about your missing photos. Make sure to connect with me as well since that was part of the assignment. Additional feedback includes:
-add your brand statement to your summary section one that's ready. 
-get recommendations from classmates/instructors
