### ISSUE TITLE
Eric Sanchez | Week03 Homework | Final Linkedin

### ISSUE THREAD

**Issue by childofthe20th** [ga-students/wdiroutcomes#58]
https://www.linkedin.com/in/esanchez2025/

**Comment by nicoleump** [comment]
Great job, Eric. A few future things to remember:
-add your brand statement to your summary section one that's ready. 
-for GA in Experience, try removing re-adding GA so the logo shows correctly. 
-add links to your projects in the GA section in Experience
-add a description for your time as a Goldsmith. 
-get recommendations from classmates/instructors
