### ISSUE TITLE
Eric Sanchez | Week03 Homework | Brand Statement

### ISSUE THREAD

**Issue by childofthe20th** [ga-students/wdiroutcomes#59]
I am a Web Developer with problem solving skills who loves to create. I seek out challenges and have an innate ability to adapt to any situation. My history as a hands-on tradesman, has given me the ability to compare old world and new world methods, which means I can offer many perspectives to tackling almost any task. My self-motivated and loyal nature means that I can keep moving forward despite the hardships of a project no matter how daunting.

**Comment by benpeterswake** [comment]
Looks good! Shows that you're a hard worker who's willing to put in the hours to get stuff done.
