### ISSUE TITLE
Brian Murphy - week 3 HW

### ISSUE THREAD

**Issue by BrianMurphy89** [ga-students/wdiroutcomes#60]
Top 5 Themes:

Team-Player
Ambitious
Goal-Oriented
Flexible
Calm / Patient

I am a junior web developer with the desire to establish a successful career. I would be a valuable addition to any team due to my calm demeanor, flexibility to handle new tasks and desire to succeed.  My ambitious nature has always made me goal-oriented, so working within timelines and remaining calm if a problem arises, does not make me falter. The opportunity within iOS / tvOS development has made want to pursue a career in tech and passion to be a successful developer.

**Comment by benpeterswake** [comment]
It's good. Has all the right features and it's going in the right direction. Just need to fix grammatically/syntax errors and stuff like that.

**Comment by tatewilson4** [comment]
This is really good, I liked how you talk about opportunity and how it drove you to get into this field. I don't think a comma is necessarily needed after 'calm if a problem arises.' It can go either way, so just reading it out loud and deciding whether it is stronger with or without the pause might be something to think about. Looks great though, can't wait to see the final brand statement!

**Comment by TrentonMarks** [comment]
Its great.  The only thing that I would do differently is the overall tense.  Its not doctrine but I find it more emotionally powerful if you speak in the future tense.  So "I WILL be a valuable addition...", "My ambitious nature MAKES me goal-oriented...".  Again, its personal preference.
