### ISSUE TITLE
Brian Murphy - LinkedIn Final

### ISSUE THREAD

**Issue by BrianMurphy89** [ga-students/wdiroutcomes#61]
https://www.linkedin.com/in/brianmurphy89/

**Comment by nicoleump** [comment]
Great job, Brian. A few future things to remember:
-add your brand statement to your summary section one that's ready. 
-for GA, try removing and re-adding GA so the logo shows correctly. 
-make sure to add a description and add links to your projects in the GA section in Experience as well.
-turn off endorsements in the skills section so you have a nice clean list of skills
-get recommendations from classmates/instructors
