### ISSUE TITLE
Samantha Whindleton | Week 4 Homework | Draft Resume

### ISSUE THREAD

**Issue by samwhindleton** [ga-students/wdiroutcomes#64]
| Week 4 Homework | Draft Resume |
| --- | --- |
| PDF | [PDF Link](https://drive.google.com/open?id=1enKXOCHQYSx37sEwY2iXI_iZGl8BiiOu) |
| Text | [Text Link](https://drive.google.com/open?id=1uZYC02T7xxNu0sjT_ZXt5-6I9gFPZ4MB) |

**Comment by nicoleump** [comment]
First, thanks for including both versions. The designed version is good when you're emailing someone directly and the text-only for when you're applying online. 

Here's my feedback on the text-only version:
-Move Experience above Education.
-Add GA to Experience where you'll feature 2-3 projects. 
-Add dates to each role in Experience.

Here's my feedback on the designed version:
-There's a lot going on so you need to make deliberate decisions. That being said, the top header is taking up too much room. Shrink the text and this section so you have more room for the important information below. 
-Phone number is missing from your contact info. Add that and remove Twitter if you're fighting for room. 
-Education and Work Experience sections need to be flipped. Rename Work Experience to Experience. 
-Add GA (featuring 2-3 projects) as the most recent role in Experience.
-Why is some of the skills listed in a different font than others. Be consistent.
