### ISSUE TITLE
Benjamin Peters Week 4 HW Resume Draft

### ISSUE THREAD

**Issue by benpeterswake** [ga-students/wdiroutcomes#65]
https://docs.google.com/document/d/1FEFMnlU-USyWeuntGV-YIzomw5ish0XJhOjN_vPyb7Y/edit?usp=sharing

**Comment by nicoleump** [comment]
Here's my feedback on your resume:
-Overall great job, Ben.
-Honestly, the only feedback I have is to remove your start date from your Education, keeping just graduation month and year.
