### ISSUE TITLE
Teilachanell |Draft Resume WIP| Wk 4 homework

### ISSUE THREAD

**Issue by tnangel1984** [ga-students/wdiroutcomes#68]
https://drive.google.com/open?id=1d1rM1MnT_TA-THxG3yu1atH_zxJlE0Up

**Comment by nicoleump** [comment]
Here's my feedback about your resume:
-Move your contact information below your name as name should be the first thing at the top of the resume.
-Un-italicize the profile and skills sections as it's hard to read.
-You'll need to tighten things up in Experience so you can get everything onto one page. Perhaps you move title and dates onto the same line as company.  Most recent experience can have a max of 5 bullet points, but I would get it down to 2-3 for all prior roles.
