### ISSUE TITLE
Tate Wilson - w04 homework

### ISSUE THREAD

**Issue by tatewilson4** [ga-students/wdiroutcomes#69]
https://docs.google.com/document/d/1ZZJk_bkMBCky5Vkq3ZZUCE7bQKU6N7a_N99CcTs0398/edit

**Comment by nicoleump** [comment]
Here's my feedback about your resume:
-The headline will go directly below your name, not your contact info section.
-For skills, make sure to use categories to group the skills. Also, WDIR is not a skill.
-Add GA as a most recent role to Experience. Feature 2-3 projects here as well like we talked about during the session.
-Education: 35 credit hours in what? General Education studies or something specific? Add that here.
-GA in Education. Reword to "Web Development Fellow" on the second line.
