### ISSUE TITLE
Victor Jaquez | Draft Resume

### ISSUE THREAD

**Issue by victorjaquez** [ga-students/wdiroutcomes#70]
https://drive.google.com/open?id=1wLC-k0YslE05nLZJXjSYIzZQ1jWoDh8a

**Comment by childofthe20th** [comment]
Looks awesome, very professional. The flow is great and the information is concise and easy to read. I have nothing to really critique hehe. Nice job!

**Comment by nicoleump** [comment]
Resume feedback:
-Remove full address
-Make sure your LinkedIn url is hyperlinked.
-Add your Github profile to your contact info section.
-Add title "Web Development Fellow" to GA in Experience. 
-Education: Add field of study to each item. Remove HS altogether.
