### ISSUE TITLE
Alec Wilbur week4 draft

### ISSUE THREAD

**Issue by lawilbur** [ga-students/wdiroutcomes#72]
https://docs.google.com/document/d/1ysyCh_4vLbnUR6_fajsOXzqqwdfxBo73YNCc-LI5kBg/edit?usp=sharing

**Comment by nicoleump** [comment]
Resume Feedback:
-Make sure Github url is hyperlinked like your email address is.
-Move GA content in Education to its own section called Web Development Experience. 
-For GA in Education, lay it out like your other education with St. Lawrence. Program and Organization. 
-Play with the margins and font size so everything fits nicely on one page.
