### ISSUE TITLE
Brian Murphy - Week 4 - Rough Draft Resume

### ISSUE THREAD

**Issue by BrianMurphy89** [ga-students/wdiroutcomes#74]
https://docs.google.com/document/d/1Hyq89XeI0ZpGzhp23wE_ENIG5LTGNsXVLo9WZ74HFRo/edit

**Comment by BrianMurphy89** [comment]
JK Here is the real link to view - https://docs.google.com/document/d/1Hyq89XeI0ZpGzhp23wE_ENIG5LTGNsXVLo9WZ74HFRo/edit?usp=sharing

**Comment by swansavage** [comment]
Good rough draft. Content is great. Really just some design suggestions for next draft: pick either bullets or numbers for your lists (I'd do bullets, personally). Make sure your capitalization/or lack thereof is consistent. Same with header sizes and spacing between sections.

**Comment by nicoleump** [comment]
Resume Feedback:
-Make name larger font size so it stands out a bit more.
-Add Github url and make sure its hyperlinked to your contact info section.
-Remove the table from your skills section and list them out using categories.
-First experience section call Web Development Experience. 
-Digital Media Consultant with GA? I believe you meant Web Development Fellow. Make sure to feature 2-3 projects here.
-Your font size and capitalization is messed up so clean all that up. 
-Where's your Education section? Add that.
-Remove References.
