### ISSUE TITLE
Natalie Wolff - Resume Draft

### ISSUE THREAD

**Issue by nataliewolff20** [ga-students/wdiroutcomes#78]
https://docs.google.com/document/d/1VVGoqIxEztkfhdZUuKZgg9e1llU9WSdFRYbX28zO3GE/edit?usp=sharing

**Comment by nicoleump** [comment]
Here's my feedback about your resume:
-Is there a reason your name is indented a bit? Make sure it is left aligned so it lines up with everything else down the page.
-Replace the existing about me with your brand statement once its ready.
-Rename "Type of Skills" to just "Skills" or "Toolkit"
-Continue to build out your list of skills or remove the categories until you have things to put in the categories.
-From all dates, remove the dash between the month and date as its unneeded and distracting. 
-For your time with Joe Coffee and Netflix can you add metrics here? For example, how many people did you manage?
-The Misc section I would rename to Interests or Activities. This section may have to come off altogether once you start adding project info for GA.
