### ISSUE TITLE
Victor Jaquez Final

### ISSUE THREAD

**Issue by victorjaquez** [ga-students/wdiroutcomes#88]
LinkedIn: http://linkedin.com/in/victorjaquez

Resume: https://drive.google.com/open?id=1i9EyaRsDycuNhetmHCJZcb-le7w_0NXG

Brand statement:

I have a desire to build, matched by my desire to always continue to learn. 

Over the years, my tasks and activities ranged from business operations, product development, software development, digital marketing, and process management.

On a personal level I love building projects and learning new skills. I am a forward thinker and optimistic person, great communicator and an emphatic listener mixed with a great entrepreneurial mindset.

**Comment by nicoleump** [comment]
For your brand statement, you're still missing the answer to the first question-what do you do? Perhaps something like: I am a web developer with a strong desire to build, matched by my desire to always continue to learn. My experience ranges from business operations to product and software development, as well as digital marketing and process management. This experience helped to develop my communication and decision-making abilities. I am a forward thinker and optimistic person, great communicator and an emphatic listener mixed with a great entrepreneurial minds and am looking forward to building scalable software applications. 

What do you think?

**Comment by victorjaquez** [comment]
Love it!!
