### ISSUE TITLE
Samantha Whindleton | Week 5 Homework | Final Brand Statement & Resume

### ISSUE THREAD

**Issue by samwhindleton** [ga-students/wdiroutcomes#92]
| Week 5 Homework | Final Brand Statement & Resume |
| --- | --- |
| Brand Statement | I'm a busy bee that loves creating scripts that complete multiple tasks in less time than it takes to take a sip of coffee. Constantly looking for efficient ways to solve problems, and opportunities to learn and grow. Let's ./start.sh something new. |
| Resume | [Link](https://drive.google.com/file/d/1-QQ7AKwlWdt17_01t_sVaOXVogooUCm2/view?usp=sharing) |

**Comment by nicoleump** [comment]
For your brand statement, you're missing the answer to question #1 - what do you do? Perhaps you could just change sentence one to "I'm a web developer (or front-end web developer) and busy-bee who loves creating....For the second sentence "I am constantly looking for...."
