### ISSUE TITLE
Alec Wilbur Final

### ISSUE THREAD

**Issue by lawilbur** [ga-students/wdiroutcomes#94]
https://docs.google.com/document/d/1ysyCh_4vLbnUR6_fajsOXzqqwdfxBo73YNCc-LI5kBg/edit?usp=sharing

https://www.linkedin.com/in/alec-wilbur/

As a developer I understand that detailed planning is an important step in any major project but being flexible and having the ability to improvise are just as critical to ensure success deployment. This attitude combined with excellent communication and a team oriented mindset are the keys that allow me efficiently and effectively conquer any task.

**Comment by nicoleump** [comment]
For your resume: flip the Web Development Experience and Experience sections. Also under your camp director role, the last line looks like it was part of something else and didn't get removed. Give it another once-over to make sure things are where they should be. :)
