### ISSUE TITLE
Samantha Whindleton | Week 6 Homework | Portfolio URL & 1st Post

### ISSUE THREAD

**Issue by samwhindleton** [ga-students/wdiroutcomes#95]
| Week 6 Homework | Portfolio URL & 1st Post |
| --- | --- |
| Portfolio Domain | https://samwhindleton.com <-- I work, visit me ^-^ |
| 1st Post | [Create Files and Folders With a Shell Script](https://github.com/samwhindleton/make-files-script) |

**Comment by nicoleump** [comment]
This is great Sam, but make sure to share the post on LinkedIn or Medium as well.
